server.servlet.application-display-name=Multimodule Service
spring.application.name=advanced-spring-boot-microservice
server.port=8080

# Management endpoints config
management.server.port=8081
management.server.address=127.0.0.1
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.health.group.liveness.include=ping
management.endpoint.health.group.readiness.include=*

# Database
spring.jpa.open-in-view=false

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.pool-name=advanced-connection-pool
spring.datasource.hikari.initialization-fail-timeout=-1

spring.datasource.hikari.data-source-properties.useServerPrepStmts=true
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048

spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:25}
spring.datasource.hikari.minimum-idle=${DB_POOL_SIZE:25}

spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=5000

# Logging
logging.level.org.apache=ERROR
logging.level.org.springframework=ERROR
logging.level.org.hibernate.SQL=ERROR

# App
app.assignments.max-batch-size=200